
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AppConfig` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AppConfig
 * 
 */
export type AppConfigModel = runtime.Types.Result.DefaultSelection<Prisma.$AppConfigPayload>

export type AggregateAppConfig = {
  _count: AppConfigCountAggregateOutputType | null
  _min: AppConfigMinAggregateOutputType | null
  _max: AppConfigMaxAggregateOutputType | null
}

export type AppConfigMinAggregateOutputType = {
  key: string | null
  value: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AppConfigMaxAggregateOutputType = {
  key: string | null
  value: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AppConfigCountAggregateOutputType = {
  key: number
  value: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AppConfigMinAggregateInputType = {
  key?: true
  value?: true
  createdAt?: true
  updatedAt?: true
}

export type AppConfigMaxAggregateInputType = {
  key?: true
  value?: true
  createdAt?: true
  updatedAt?: true
}

export type AppConfigCountAggregateInputType = {
  key?: true
  value?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AppConfigAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AppConfig to aggregate.
   */
  where?: Prisma.AppConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppConfigs to fetch.
   */
  orderBy?: Prisma.AppConfigOrderByWithRelationInput | Prisma.AppConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AppConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AppConfigs
  **/
  _count?: true | AppConfigCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AppConfigMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AppConfigMaxAggregateInputType
}

export type GetAppConfigAggregateType<T extends AppConfigAggregateArgs> = {
      [P in keyof T & keyof AggregateAppConfig]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAppConfig[P]>
    : Prisma.GetScalarType<T[P], AggregateAppConfig[P]>
}




export type AppConfigGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AppConfigWhereInput
  orderBy?: Prisma.AppConfigOrderByWithAggregationInput | Prisma.AppConfigOrderByWithAggregationInput[]
  by: Prisma.AppConfigScalarFieldEnum[] | Prisma.AppConfigScalarFieldEnum
  having?: Prisma.AppConfigScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AppConfigCountAggregateInputType | true
  _min?: AppConfigMinAggregateInputType
  _max?: AppConfigMaxAggregateInputType
}

export type AppConfigGroupByOutputType = {
  key: string
  value: string
  createdAt: Date
  updatedAt: Date
  _count: AppConfigCountAggregateOutputType | null
  _min: AppConfigMinAggregateOutputType | null
  _max: AppConfigMaxAggregateOutputType | null
}

type GetAppConfigGroupByPayload<T extends AppConfigGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AppConfigGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AppConfigGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AppConfigGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AppConfigGroupByOutputType[P]>
      }
    >
  >



export type AppConfigWhereInput = {
  AND?: Prisma.AppConfigWhereInput | Prisma.AppConfigWhereInput[]
  OR?: Prisma.AppConfigWhereInput[]
  NOT?: Prisma.AppConfigWhereInput | Prisma.AppConfigWhereInput[]
  key?: Prisma.StringFilter<"AppConfig"> | string
  value?: Prisma.StringFilter<"AppConfig"> | string
  createdAt?: Prisma.DateTimeFilter<"AppConfig"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AppConfig"> | Date | string
}

export type AppConfigOrderByWithRelationInput = {
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AppConfigWhereUniqueInput = Prisma.AtLeast<{
  key?: string
  AND?: Prisma.AppConfigWhereInput | Prisma.AppConfigWhereInput[]
  OR?: Prisma.AppConfigWhereInput[]
  NOT?: Prisma.AppConfigWhereInput | Prisma.AppConfigWhereInput[]
  value?: Prisma.StringFilter<"AppConfig"> | string
  createdAt?: Prisma.DateTimeFilter<"AppConfig"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AppConfig"> | Date | string
}, "key">

export type AppConfigOrderByWithAggregationInput = {
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AppConfigCountOrderByAggregateInput
  _max?: Prisma.AppConfigMaxOrderByAggregateInput
  _min?: Prisma.AppConfigMinOrderByAggregateInput
}

export type AppConfigScalarWhereWithAggregatesInput = {
  AND?: Prisma.AppConfigScalarWhereWithAggregatesInput | Prisma.AppConfigScalarWhereWithAggregatesInput[]
  OR?: Prisma.AppConfigScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AppConfigScalarWhereWithAggregatesInput | Prisma.AppConfigScalarWhereWithAggregatesInput[]
  key?: Prisma.StringWithAggregatesFilter<"AppConfig"> | string
  value?: Prisma.StringWithAggregatesFilter<"AppConfig"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AppConfig"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AppConfig"> | Date | string
}

export type AppConfigCreateInput = {
  key: string
  value: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AppConfigUncheckedCreateInput = {
  key: string
  value: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AppConfigUpdateInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AppConfigUncheckedUpdateInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AppConfigCreateManyInput = {
  key: string
  value: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AppConfigUpdateManyMutationInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AppConfigUncheckedUpdateManyInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AppConfigCountOrderByAggregateInput = {
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AppConfigMaxOrderByAggregateInput = {
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AppConfigMinOrderByAggregateInput = {
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type AppConfigSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  value?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["appConfig"]>

export type AppConfigSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  value?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["appConfig"]>

export type AppConfigSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  value?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["appConfig"]>

export type AppConfigSelectScalar = {
  key?: boolean
  value?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AppConfigOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"key" | "value" | "createdAt" | "updatedAt", ExtArgs["result"]["appConfig"]>

export type $AppConfigPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AppConfig"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    key: string
    value: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["appConfig"]>
  composites: {}
}

export type AppConfigGetPayload<S extends boolean | null | undefined | AppConfigDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AppConfigPayload, S>

export type AppConfigCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AppConfigFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AppConfigCountAggregateInputType | true
  }

export interface AppConfigDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AppConfig'], meta: { name: 'AppConfig' } }
  /**
   * Find zero or one AppConfig that matches the filter.
   * @param {AppConfigFindUniqueArgs} args - Arguments to find a AppConfig
   * @example
   * // Get one AppConfig
   * const appConfig = await prisma.appConfig.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AppConfigFindUniqueArgs>(args: Prisma.SelectSubset<T, AppConfigFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AppConfigClient<runtime.Types.Result.GetResult<Prisma.$AppConfigPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AppConfig that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AppConfigFindUniqueOrThrowArgs} args - Arguments to find a AppConfig
   * @example
   * // Get one AppConfig
   * const appConfig = await prisma.appConfig.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AppConfigFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AppConfigFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppConfigClient<runtime.Types.Result.GetResult<Prisma.$AppConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AppConfig that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppConfigFindFirstArgs} args - Arguments to find a AppConfig
   * @example
   * // Get one AppConfig
   * const appConfig = await prisma.appConfig.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AppConfigFindFirstArgs>(args?: Prisma.SelectSubset<T, AppConfigFindFirstArgs<ExtArgs>>): Prisma.Prisma__AppConfigClient<runtime.Types.Result.GetResult<Prisma.$AppConfigPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AppConfig that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppConfigFindFirstOrThrowArgs} args - Arguments to find a AppConfig
   * @example
   * // Get one AppConfig
   * const appConfig = await prisma.appConfig.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AppConfigFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AppConfigFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppConfigClient<runtime.Types.Result.GetResult<Prisma.$AppConfigPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AppConfigs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppConfigFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AppConfigs
   * const appConfigs = await prisma.appConfig.findMany()
   * 
   * // Get first 10 AppConfigs
   * const appConfigs = await prisma.appConfig.findMany({ take: 10 })
   * 
   * // Only select the `key`
   * const appConfigWithKeyOnly = await prisma.appConfig.findMany({ select: { key: true } })
   * 
   */
  findMany<T extends AppConfigFindManyArgs>(args?: Prisma.SelectSubset<T, AppConfigFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppConfigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AppConfig.
   * @param {AppConfigCreateArgs} args - Arguments to create a AppConfig.
   * @example
   * // Create one AppConfig
   * const AppConfig = await prisma.appConfig.create({
   *   data: {
   *     // ... data to create a AppConfig
   *   }
   * })
   * 
   */
  create<T extends AppConfigCreateArgs>(args: Prisma.SelectSubset<T, AppConfigCreateArgs<ExtArgs>>): Prisma.Prisma__AppConfigClient<runtime.Types.Result.GetResult<Prisma.$AppConfigPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AppConfigs.
   * @param {AppConfigCreateManyArgs} args - Arguments to create many AppConfigs.
   * @example
   * // Create many AppConfigs
   * const appConfig = await prisma.appConfig.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AppConfigCreateManyArgs>(args?: Prisma.SelectSubset<T, AppConfigCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AppConfigs and returns the data saved in the database.
   * @param {AppConfigCreateManyAndReturnArgs} args - Arguments to create many AppConfigs.
   * @example
   * // Create many AppConfigs
   * const appConfig = await prisma.appConfig.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AppConfigs and only return the `key`
   * const appConfigWithKeyOnly = await prisma.appConfig.createManyAndReturn({
   *   select: { key: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AppConfigCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AppConfigCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppConfigPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AppConfig.
   * @param {AppConfigDeleteArgs} args - Arguments to delete one AppConfig.
   * @example
   * // Delete one AppConfig
   * const AppConfig = await prisma.appConfig.delete({
   *   where: {
   *     // ... filter to delete one AppConfig
   *   }
   * })
   * 
   */
  delete<T extends AppConfigDeleteArgs>(args: Prisma.SelectSubset<T, AppConfigDeleteArgs<ExtArgs>>): Prisma.Prisma__AppConfigClient<runtime.Types.Result.GetResult<Prisma.$AppConfigPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AppConfig.
   * @param {AppConfigUpdateArgs} args - Arguments to update one AppConfig.
   * @example
   * // Update one AppConfig
   * const appConfig = await prisma.appConfig.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AppConfigUpdateArgs>(args: Prisma.SelectSubset<T, AppConfigUpdateArgs<ExtArgs>>): Prisma.Prisma__AppConfigClient<runtime.Types.Result.GetResult<Prisma.$AppConfigPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AppConfigs.
   * @param {AppConfigDeleteManyArgs} args - Arguments to filter AppConfigs to delete.
   * @example
   * // Delete a few AppConfigs
   * const { count } = await prisma.appConfig.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AppConfigDeleteManyArgs>(args?: Prisma.SelectSubset<T, AppConfigDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AppConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppConfigUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AppConfigs
   * const appConfig = await prisma.appConfig.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AppConfigUpdateManyArgs>(args: Prisma.SelectSubset<T, AppConfigUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AppConfigs and returns the data updated in the database.
   * @param {AppConfigUpdateManyAndReturnArgs} args - Arguments to update many AppConfigs.
   * @example
   * // Update many AppConfigs
   * const appConfig = await prisma.appConfig.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AppConfigs and only return the `key`
   * const appConfigWithKeyOnly = await prisma.appConfig.updateManyAndReturn({
   *   select: { key: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AppConfigUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AppConfigUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppConfigPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AppConfig.
   * @param {AppConfigUpsertArgs} args - Arguments to update or create a AppConfig.
   * @example
   * // Update or create a AppConfig
   * const appConfig = await prisma.appConfig.upsert({
   *   create: {
   *     // ... data to create a AppConfig
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AppConfig we want to update
   *   }
   * })
   */
  upsert<T extends AppConfigUpsertArgs>(args: Prisma.SelectSubset<T, AppConfigUpsertArgs<ExtArgs>>): Prisma.Prisma__AppConfigClient<runtime.Types.Result.GetResult<Prisma.$AppConfigPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AppConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppConfigCountArgs} args - Arguments to filter AppConfigs to count.
   * @example
   * // Count the number of AppConfigs
   * const count = await prisma.appConfig.count({
   *   where: {
   *     // ... the filter for the AppConfigs we want to count
   *   }
   * })
  **/
  count<T extends AppConfigCountArgs>(
    args?: Prisma.Subset<T, AppConfigCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AppConfigCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AppConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppConfigAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AppConfigAggregateArgs>(args: Prisma.Subset<T, AppConfigAggregateArgs>): Prisma.PrismaPromise<GetAppConfigAggregateType<T>>

  /**
   * Group by AppConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppConfigGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AppConfigGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AppConfigGroupByArgs['orderBy'] }
      : { orderBy?: AppConfigGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AppConfigGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAppConfigGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AppConfig model
 */
readonly fields: AppConfigFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AppConfig.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AppConfigClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AppConfig model
 */
export interface AppConfigFieldRefs {
  readonly key: Prisma.FieldRef<"AppConfig", 'String'>
  readonly value: Prisma.FieldRef<"AppConfig", 'String'>
  readonly createdAt: Prisma.FieldRef<"AppConfig", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AppConfig", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AppConfig findUnique
 */
export type AppConfigFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppConfig
   */
  select?: Prisma.AppConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppConfig
   */
  omit?: Prisma.AppConfigOmit<ExtArgs> | null
  /**
   * Filter, which AppConfig to fetch.
   */
  where: Prisma.AppConfigWhereUniqueInput
}

/**
 * AppConfig findUniqueOrThrow
 */
export type AppConfigFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppConfig
   */
  select?: Prisma.AppConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppConfig
   */
  omit?: Prisma.AppConfigOmit<ExtArgs> | null
  /**
   * Filter, which AppConfig to fetch.
   */
  where: Prisma.AppConfigWhereUniqueInput
}

/**
 * AppConfig findFirst
 */
export type AppConfigFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppConfig
   */
  select?: Prisma.AppConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppConfig
   */
  omit?: Prisma.AppConfigOmit<ExtArgs> | null
  /**
   * Filter, which AppConfig to fetch.
   */
  where?: Prisma.AppConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppConfigs to fetch.
   */
  orderBy?: Prisma.AppConfigOrderByWithRelationInput | Prisma.AppConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AppConfigs.
   */
  cursor?: Prisma.AppConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AppConfigs.
   */
  distinct?: Prisma.AppConfigScalarFieldEnum | Prisma.AppConfigScalarFieldEnum[]
}

/**
 * AppConfig findFirstOrThrow
 */
export type AppConfigFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppConfig
   */
  select?: Prisma.AppConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppConfig
   */
  omit?: Prisma.AppConfigOmit<ExtArgs> | null
  /**
   * Filter, which AppConfig to fetch.
   */
  where?: Prisma.AppConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppConfigs to fetch.
   */
  orderBy?: Prisma.AppConfigOrderByWithRelationInput | Prisma.AppConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AppConfigs.
   */
  cursor?: Prisma.AppConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AppConfigs.
   */
  distinct?: Prisma.AppConfigScalarFieldEnum | Prisma.AppConfigScalarFieldEnum[]
}

/**
 * AppConfig findMany
 */
export type AppConfigFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppConfig
   */
  select?: Prisma.AppConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppConfig
   */
  omit?: Prisma.AppConfigOmit<ExtArgs> | null
  /**
   * Filter, which AppConfigs to fetch.
   */
  where?: Prisma.AppConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppConfigs to fetch.
   */
  orderBy?: Prisma.AppConfigOrderByWithRelationInput | Prisma.AppConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AppConfigs.
   */
  cursor?: Prisma.AppConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppConfigs.
   */
  skip?: number
  distinct?: Prisma.AppConfigScalarFieldEnum | Prisma.AppConfigScalarFieldEnum[]
}

/**
 * AppConfig create
 */
export type AppConfigCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppConfig
   */
  select?: Prisma.AppConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppConfig
   */
  omit?: Prisma.AppConfigOmit<ExtArgs> | null
  /**
   * The data needed to create a AppConfig.
   */
  data: Prisma.XOR<Prisma.AppConfigCreateInput, Prisma.AppConfigUncheckedCreateInput>
}

/**
 * AppConfig createMany
 */
export type AppConfigCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AppConfigs.
   */
  data: Prisma.AppConfigCreateManyInput | Prisma.AppConfigCreateManyInput[]
}

/**
 * AppConfig createManyAndReturn
 */
export type AppConfigCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppConfig
   */
  select?: Prisma.AppConfigSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AppConfig
   */
  omit?: Prisma.AppConfigOmit<ExtArgs> | null
  /**
   * The data used to create many AppConfigs.
   */
  data: Prisma.AppConfigCreateManyInput | Prisma.AppConfigCreateManyInput[]
}

/**
 * AppConfig update
 */
export type AppConfigUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppConfig
   */
  select?: Prisma.AppConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppConfig
   */
  omit?: Prisma.AppConfigOmit<ExtArgs> | null
  /**
   * The data needed to update a AppConfig.
   */
  data: Prisma.XOR<Prisma.AppConfigUpdateInput, Prisma.AppConfigUncheckedUpdateInput>
  /**
   * Choose, which AppConfig to update.
   */
  where: Prisma.AppConfigWhereUniqueInput
}

/**
 * AppConfig updateMany
 */
export type AppConfigUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AppConfigs.
   */
  data: Prisma.XOR<Prisma.AppConfigUpdateManyMutationInput, Prisma.AppConfigUncheckedUpdateManyInput>
  /**
   * Filter which AppConfigs to update
   */
  where?: Prisma.AppConfigWhereInput
  /**
   * Limit how many AppConfigs to update.
   */
  limit?: number
}

/**
 * AppConfig updateManyAndReturn
 */
export type AppConfigUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppConfig
   */
  select?: Prisma.AppConfigSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AppConfig
   */
  omit?: Prisma.AppConfigOmit<ExtArgs> | null
  /**
   * The data used to update AppConfigs.
   */
  data: Prisma.XOR<Prisma.AppConfigUpdateManyMutationInput, Prisma.AppConfigUncheckedUpdateManyInput>
  /**
   * Filter which AppConfigs to update
   */
  where?: Prisma.AppConfigWhereInput
  /**
   * Limit how many AppConfigs to update.
   */
  limit?: number
}

/**
 * AppConfig upsert
 */
export type AppConfigUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppConfig
   */
  select?: Prisma.AppConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppConfig
   */
  omit?: Prisma.AppConfigOmit<ExtArgs> | null
  /**
   * The filter to search for the AppConfig to update in case it exists.
   */
  where: Prisma.AppConfigWhereUniqueInput
  /**
   * In case the AppConfig found by the `where` argument doesn't exist, create a new AppConfig with this data.
   */
  create: Prisma.XOR<Prisma.AppConfigCreateInput, Prisma.AppConfigUncheckedCreateInput>
  /**
   * In case the AppConfig was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AppConfigUpdateInput, Prisma.AppConfigUncheckedUpdateInput>
}

/**
 * AppConfig delete
 */
export type AppConfigDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppConfig
   */
  select?: Prisma.AppConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppConfig
   */
  omit?: Prisma.AppConfigOmit<ExtArgs> | null
  /**
   * Filter which AppConfig to delete.
   */
  where: Prisma.AppConfigWhereUniqueInput
}

/**
 * AppConfig deleteMany
 */
export type AppConfigDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AppConfigs to delete
   */
  where?: Prisma.AppConfigWhereInput
  /**
   * Limit how many AppConfigs to delete.
   */
  limit?: number
}

/**
 * AppConfig without action
 */
export type AppConfigDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppConfig
   */
  select?: Prisma.AppConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppConfig
   */
  omit?: Prisma.AppConfigOmit<ExtArgs> | null
}
