
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Diary` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Diary
 * 
 */
export type DiaryModel = runtime.Types.Result.DefaultSelection<Prisma.$DiaryPayload>

export type AggregateDiary = {
  _count: DiaryCountAggregateOutputType | null
  _avg: DiaryAvgAggregateOutputType | null
  _sum: DiarySumAggregateOutputType | null
  _min: DiaryMinAggregateOutputType | null
  _max: DiaryMaxAggregateOutputType | null
}

export type DiaryAvgAggregateOutputType = {
  date: number | null
}

export type DiarySumAggregateOutputType = {
  date: bigint | null
}

export type DiaryMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  date: bigint | null
  content: string | null
  color: string | null
}

export type DiaryMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  date: bigint | null
  content: string | null
  color: string | null
}

export type DiaryCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  date: number
  content: number
  color: number
  _all: number
}


export type DiaryAvgAggregateInputType = {
  date?: true
}

export type DiarySumAggregateInputType = {
  date?: true
}

export type DiaryMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  date?: true
  content?: true
  color?: true
}

export type DiaryMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  date?: true
  content?: true
  color?: true
}

export type DiaryCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  date?: true
  content?: true
  color?: true
  _all?: true
}

export type DiaryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Diary to aggregate.
   */
  where?: Prisma.DiaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Diaries to fetch.
   */
  orderBy?: Prisma.DiaryOrderByWithRelationInput | Prisma.DiaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DiaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Diaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Diaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Diaries
  **/
  _count?: true | DiaryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DiaryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DiarySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DiaryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DiaryMaxAggregateInputType
}

export type GetDiaryAggregateType<T extends DiaryAggregateArgs> = {
      [P in keyof T & keyof AggregateDiary]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDiary[P]>
    : Prisma.GetScalarType<T[P], AggregateDiary[P]>
}




export type DiaryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DiaryWhereInput
  orderBy?: Prisma.DiaryOrderByWithAggregationInput | Prisma.DiaryOrderByWithAggregationInput[]
  by: Prisma.DiaryScalarFieldEnum[] | Prisma.DiaryScalarFieldEnum
  having?: Prisma.DiaryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DiaryCountAggregateInputType | true
  _avg?: DiaryAvgAggregateInputType
  _sum?: DiarySumAggregateInputType
  _min?: DiaryMinAggregateInputType
  _max?: DiaryMaxAggregateInputType
}

export type DiaryGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  date: bigint
  content: string
  color: string | null
  _count: DiaryCountAggregateOutputType | null
  _avg: DiaryAvgAggregateOutputType | null
  _sum: DiarySumAggregateOutputType | null
  _min: DiaryMinAggregateOutputType | null
  _max: DiaryMaxAggregateOutputType | null
}

type GetDiaryGroupByPayload<T extends DiaryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DiaryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DiaryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DiaryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DiaryGroupByOutputType[P]>
      }
    >
  >



export type DiaryWhereInput = {
  AND?: Prisma.DiaryWhereInput | Prisma.DiaryWhereInput[]
  OR?: Prisma.DiaryWhereInput[]
  NOT?: Prisma.DiaryWhereInput | Prisma.DiaryWhereInput[]
  id?: Prisma.StringFilter<"Diary"> | string
  createdAt?: Prisma.DateTimeFilter<"Diary"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Diary"> | Date | string
  date?: Prisma.BigIntFilter<"Diary"> | bigint | number
  content?: Prisma.StringFilter<"Diary"> | string
  color?: Prisma.StringNullableFilter<"Diary"> | string | null
}

export type DiaryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  date?: Prisma.SortOrder
  content?: Prisma.SortOrder
  color?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type DiaryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  date?: bigint | number
  AND?: Prisma.DiaryWhereInput | Prisma.DiaryWhereInput[]
  OR?: Prisma.DiaryWhereInput[]
  NOT?: Prisma.DiaryWhereInput | Prisma.DiaryWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Diary"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Diary"> | Date | string
  content?: Prisma.StringFilter<"Diary"> | string
  color?: Prisma.StringNullableFilter<"Diary"> | string | null
}, "id" | "date">

export type DiaryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  date?: Prisma.SortOrder
  content?: Prisma.SortOrder
  color?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.DiaryCountOrderByAggregateInput
  _avg?: Prisma.DiaryAvgOrderByAggregateInput
  _max?: Prisma.DiaryMaxOrderByAggregateInput
  _min?: Prisma.DiaryMinOrderByAggregateInput
  _sum?: Prisma.DiarySumOrderByAggregateInput
}

export type DiaryScalarWhereWithAggregatesInput = {
  AND?: Prisma.DiaryScalarWhereWithAggregatesInput | Prisma.DiaryScalarWhereWithAggregatesInput[]
  OR?: Prisma.DiaryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DiaryScalarWhereWithAggregatesInput | Prisma.DiaryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Diary"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Diary"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Diary"> | Date | string
  date?: Prisma.BigIntWithAggregatesFilter<"Diary"> | bigint | number
  content?: Prisma.StringWithAggregatesFilter<"Diary"> | string
  color?: Prisma.StringNullableWithAggregatesFilter<"Diary"> | string | null
}

export type DiaryCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  date: bigint | number
  content?: string
  color?: string | null
}

export type DiaryUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  date: bigint | number
  content?: string
  color?: string | null
}

export type DiaryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  date?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DiaryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  date?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DiaryCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  date: bigint | number
  content?: string
  color?: string | null
}

export type DiaryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  date?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DiaryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  date?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DiaryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  date?: Prisma.SortOrder
  content?: Prisma.SortOrder
  color?: Prisma.SortOrder
}

export type DiaryAvgOrderByAggregateInput = {
  date?: Prisma.SortOrder
}

export type DiaryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  date?: Prisma.SortOrder
  content?: Prisma.SortOrder
  color?: Prisma.SortOrder
}

export type DiaryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  date?: Prisma.SortOrder
  content?: Prisma.SortOrder
  color?: Prisma.SortOrder
}

export type DiarySumOrderByAggregateInput = {
  date?: Prisma.SortOrder
}

export type BigIntFieldUpdateOperationsInput = {
  set?: bigint | number
  increment?: bigint | number
  decrement?: bigint | number
  multiply?: bigint | number
  divide?: bigint | number
}



export type DiarySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  date?: boolean
  content?: boolean
  color?: boolean
}, ExtArgs["result"]["diary"]>

export type DiarySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  date?: boolean
  content?: boolean
  color?: boolean
}, ExtArgs["result"]["diary"]>

export type DiarySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  date?: boolean
  content?: boolean
  color?: boolean
}, ExtArgs["result"]["diary"]>

export type DiarySelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  date?: boolean
  content?: boolean
  color?: boolean
}

export type DiaryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "date" | "content" | "color", ExtArgs["result"]["diary"]>

export type $DiaryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Diary"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    date: bigint
    content: string
    color: string | null
  }, ExtArgs["result"]["diary"]>
  composites: {}
}

export type DiaryGetPayload<S extends boolean | null | undefined | DiaryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DiaryPayload, S>

export type DiaryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DiaryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DiaryCountAggregateInputType | true
  }

export interface DiaryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Diary'], meta: { name: 'Diary' } }
  /**
   * Find zero or one Diary that matches the filter.
   * @param {DiaryFindUniqueArgs} args - Arguments to find a Diary
   * @example
   * // Get one Diary
   * const diary = await prisma.diary.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DiaryFindUniqueArgs>(args: Prisma.SelectSubset<T, DiaryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DiaryClient<runtime.Types.Result.GetResult<Prisma.$DiaryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Diary that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DiaryFindUniqueOrThrowArgs} args - Arguments to find a Diary
   * @example
   * // Get one Diary
   * const diary = await prisma.diary.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DiaryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DiaryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DiaryClient<runtime.Types.Result.GetResult<Prisma.$DiaryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Diary that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiaryFindFirstArgs} args - Arguments to find a Diary
   * @example
   * // Get one Diary
   * const diary = await prisma.diary.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DiaryFindFirstArgs>(args?: Prisma.SelectSubset<T, DiaryFindFirstArgs<ExtArgs>>): Prisma.Prisma__DiaryClient<runtime.Types.Result.GetResult<Prisma.$DiaryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Diary that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiaryFindFirstOrThrowArgs} args - Arguments to find a Diary
   * @example
   * // Get one Diary
   * const diary = await prisma.diary.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DiaryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DiaryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DiaryClient<runtime.Types.Result.GetResult<Prisma.$DiaryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Diaries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiaryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Diaries
   * const diaries = await prisma.diary.findMany()
   * 
   * // Get first 10 Diaries
   * const diaries = await prisma.diary.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const diaryWithIdOnly = await prisma.diary.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DiaryFindManyArgs>(args?: Prisma.SelectSubset<T, DiaryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DiaryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Diary.
   * @param {DiaryCreateArgs} args - Arguments to create a Diary.
   * @example
   * // Create one Diary
   * const Diary = await prisma.diary.create({
   *   data: {
   *     // ... data to create a Diary
   *   }
   * })
   * 
   */
  create<T extends DiaryCreateArgs>(args: Prisma.SelectSubset<T, DiaryCreateArgs<ExtArgs>>): Prisma.Prisma__DiaryClient<runtime.Types.Result.GetResult<Prisma.$DiaryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Diaries.
   * @param {DiaryCreateManyArgs} args - Arguments to create many Diaries.
   * @example
   * // Create many Diaries
   * const diary = await prisma.diary.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DiaryCreateManyArgs>(args?: Prisma.SelectSubset<T, DiaryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Diaries and returns the data saved in the database.
   * @param {DiaryCreateManyAndReturnArgs} args - Arguments to create many Diaries.
   * @example
   * // Create many Diaries
   * const diary = await prisma.diary.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Diaries and only return the `id`
   * const diaryWithIdOnly = await prisma.diary.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DiaryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DiaryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DiaryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Diary.
   * @param {DiaryDeleteArgs} args - Arguments to delete one Diary.
   * @example
   * // Delete one Diary
   * const Diary = await prisma.diary.delete({
   *   where: {
   *     // ... filter to delete one Diary
   *   }
   * })
   * 
   */
  delete<T extends DiaryDeleteArgs>(args: Prisma.SelectSubset<T, DiaryDeleteArgs<ExtArgs>>): Prisma.Prisma__DiaryClient<runtime.Types.Result.GetResult<Prisma.$DiaryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Diary.
   * @param {DiaryUpdateArgs} args - Arguments to update one Diary.
   * @example
   * // Update one Diary
   * const diary = await prisma.diary.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DiaryUpdateArgs>(args: Prisma.SelectSubset<T, DiaryUpdateArgs<ExtArgs>>): Prisma.Prisma__DiaryClient<runtime.Types.Result.GetResult<Prisma.$DiaryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Diaries.
   * @param {DiaryDeleteManyArgs} args - Arguments to filter Diaries to delete.
   * @example
   * // Delete a few Diaries
   * const { count } = await prisma.diary.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DiaryDeleteManyArgs>(args?: Prisma.SelectSubset<T, DiaryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Diaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiaryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Diaries
   * const diary = await prisma.diary.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DiaryUpdateManyArgs>(args: Prisma.SelectSubset<T, DiaryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Diaries and returns the data updated in the database.
   * @param {DiaryUpdateManyAndReturnArgs} args - Arguments to update many Diaries.
   * @example
   * // Update many Diaries
   * const diary = await prisma.diary.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Diaries and only return the `id`
   * const diaryWithIdOnly = await prisma.diary.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DiaryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DiaryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DiaryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Diary.
   * @param {DiaryUpsertArgs} args - Arguments to update or create a Diary.
   * @example
   * // Update or create a Diary
   * const diary = await prisma.diary.upsert({
   *   create: {
   *     // ... data to create a Diary
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Diary we want to update
   *   }
   * })
   */
  upsert<T extends DiaryUpsertArgs>(args: Prisma.SelectSubset<T, DiaryUpsertArgs<ExtArgs>>): Prisma.Prisma__DiaryClient<runtime.Types.Result.GetResult<Prisma.$DiaryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Diaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiaryCountArgs} args - Arguments to filter Diaries to count.
   * @example
   * // Count the number of Diaries
   * const count = await prisma.diary.count({
   *   where: {
   *     // ... the filter for the Diaries we want to count
   *   }
   * })
  **/
  count<T extends DiaryCountArgs>(
    args?: Prisma.Subset<T, DiaryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DiaryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Diary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiaryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DiaryAggregateArgs>(args: Prisma.Subset<T, DiaryAggregateArgs>): Prisma.PrismaPromise<GetDiaryAggregateType<T>>

  /**
   * Group by Diary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiaryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DiaryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DiaryGroupByArgs['orderBy'] }
      : { orderBy?: DiaryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DiaryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDiaryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Diary model
 */
readonly fields: DiaryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Diary.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DiaryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Diary model
 */
export interface DiaryFieldRefs {
  readonly id: Prisma.FieldRef<"Diary", 'String'>
  readonly createdAt: Prisma.FieldRef<"Diary", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Diary", 'DateTime'>
  readonly date: Prisma.FieldRef<"Diary", 'BigInt'>
  readonly content: Prisma.FieldRef<"Diary", 'String'>
  readonly color: Prisma.FieldRef<"Diary", 'String'>
}
    

// Custom InputTypes
/**
 * Diary findUnique
 */
export type DiaryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Diary
   */
  select?: Prisma.DiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Diary
   */
  omit?: Prisma.DiaryOmit<ExtArgs> | null
  /**
   * Filter, which Diary to fetch.
   */
  where: Prisma.DiaryWhereUniqueInput
}

/**
 * Diary findUniqueOrThrow
 */
export type DiaryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Diary
   */
  select?: Prisma.DiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Diary
   */
  omit?: Prisma.DiaryOmit<ExtArgs> | null
  /**
   * Filter, which Diary to fetch.
   */
  where: Prisma.DiaryWhereUniqueInput
}

/**
 * Diary findFirst
 */
export type DiaryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Diary
   */
  select?: Prisma.DiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Diary
   */
  omit?: Prisma.DiaryOmit<ExtArgs> | null
  /**
   * Filter, which Diary to fetch.
   */
  where?: Prisma.DiaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Diaries to fetch.
   */
  orderBy?: Prisma.DiaryOrderByWithRelationInput | Prisma.DiaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Diaries.
   */
  cursor?: Prisma.DiaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Diaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Diaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Diaries.
   */
  distinct?: Prisma.DiaryScalarFieldEnum | Prisma.DiaryScalarFieldEnum[]
}

/**
 * Diary findFirstOrThrow
 */
export type DiaryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Diary
   */
  select?: Prisma.DiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Diary
   */
  omit?: Prisma.DiaryOmit<ExtArgs> | null
  /**
   * Filter, which Diary to fetch.
   */
  where?: Prisma.DiaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Diaries to fetch.
   */
  orderBy?: Prisma.DiaryOrderByWithRelationInput | Prisma.DiaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Diaries.
   */
  cursor?: Prisma.DiaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Diaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Diaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Diaries.
   */
  distinct?: Prisma.DiaryScalarFieldEnum | Prisma.DiaryScalarFieldEnum[]
}

/**
 * Diary findMany
 */
export type DiaryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Diary
   */
  select?: Prisma.DiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Diary
   */
  omit?: Prisma.DiaryOmit<ExtArgs> | null
  /**
   * Filter, which Diaries to fetch.
   */
  where?: Prisma.DiaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Diaries to fetch.
   */
  orderBy?: Prisma.DiaryOrderByWithRelationInput | Prisma.DiaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Diaries.
   */
  cursor?: Prisma.DiaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Diaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Diaries.
   */
  skip?: number
  distinct?: Prisma.DiaryScalarFieldEnum | Prisma.DiaryScalarFieldEnum[]
}

/**
 * Diary create
 */
export type DiaryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Diary
   */
  select?: Prisma.DiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Diary
   */
  omit?: Prisma.DiaryOmit<ExtArgs> | null
  /**
   * The data needed to create a Diary.
   */
  data: Prisma.XOR<Prisma.DiaryCreateInput, Prisma.DiaryUncheckedCreateInput>
}

/**
 * Diary createMany
 */
export type DiaryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Diaries.
   */
  data: Prisma.DiaryCreateManyInput | Prisma.DiaryCreateManyInput[]
}

/**
 * Diary createManyAndReturn
 */
export type DiaryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Diary
   */
  select?: Prisma.DiarySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Diary
   */
  omit?: Prisma.DiaryOmit<ExtArgs> | null
  /**
   * The data used to create many Diaries.
   */
  data: Prisma.DiaryCreateManyInput | Prisma.DiaryCreateManyInput[]
}

/**
 * Diary update
 */
export type DiaryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Diary
   */
  select?: Prisma.DiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Diary
   */
  omit?: Prisma.DiaryOmit<ExtArgs> | null
  /**
   * The data needed to update a Diary.
   */
  data: Prisma.XOR<Prisma.DiaryUpdateInput, Prisma.DiaryUncheckedUpdateInput>
  /**
   * Choose, which Diary to update.
   */
  where: Prisma.DiaryWhereUniqueInput
}

/**
 * Diary updateMany
 */
export type DiaryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Diaries.
   */
  data: Prisma.XOR<Prisma.DiaryUpdateManyMutationInput, Prisma.DiaryUncheckedUpdateManyInput>
  /**
   * Filter which Diaries to update
   */
  where?: Prisma.DiaryWhereInput
  /**
   * Limit how many Diaries to update.
   */
  limit?: number
}

/**
 * Diary updateManyAndReturn
 */
export type DiaryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Diary
   */
  select?: Prisma.DiarySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Diary
   */
  omit?: Prisma.DiaryOmit<ExtArgs> | null
  /**
   * The data used to update Diaries.
   */
  data: Prisma.XOR<Prisma.DiaryUpdateManyMutationInput, Prisma.DiaryUncheckedUpdateManyInput>
  /**
   * Filter which Diaries to update
   */
  where?: Prisma.DiaryWhereInput
  /**
   * Limit how many Diaries to update.
   */
  limit?: number
}

/**
 * Diary upsert
 */
export type DiaryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Diary
   */
  select?: Prisma.DiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Diary
   */
  omit?: Prisma.DiaryOmit<ExtArgs> | null
  /**
   * The filter to search for the Diary to update in case it exists.
   */
  where: Prisma.DiaryWhereUniqueInput
  /**
   * In case the Diary found by the `where` argument doesn't exist, create a new Diary with this data.
   */
  create: Prisma.XOR<Prisma.DiaryCreateInput, Prisma.DiaryUncheckedCreateInput>
  /**
   * In case the Diary was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DiaryUpdateInput, Prisma.DiaryUncheckedUpdateInput>
}

/**
 * Diary delete
 */
export type DiaryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Diary
   */
  select?: Prisma.DiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Diary
   */
  omit?: Prisma.DiaryOmit<ExtArgs> | null
  /**
   * Filter which Diary to delete.
   */
  where: Prisma.DiaryWhereUniqueInput
}

/**
 * Diary deleteMany
 */
export type DiaryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Diaries to delete
   */
  where?: Prisma.DiaryWhereInput
  /**
   * Limit how many Diaries to delete.
   */
  limit?: number
}

/**
 * Diary without action
 */
export type DiaryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Diary
   */
  select?: Prisma.DiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Diary
   */
  omit?: Prisma.DiaryOmit<ExtArgs> | null
}
