import { useState } from 'react'
import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { SettingO, UnderwayO, Search, Edit } from '@react-vant/icons';
import { Field, Button, Toast, Space, ActionBar, Tag } from 'react-vant';
import { useDiaryList } from 'services/diary';
import { getDiaryConfig } from 'lib/loadConfig';
import { DiaryItem } from 'components/DiaryItem';

interface Props {
    buttonColor: string
}

const Home: NextPage<Props> = (props) => {
    const { buttonColor } = props
    const { data, error } = useDiaryList('202203')
    const [clickDiary, setClickDiary] = useState<number | undefined>(undefined);

    return (
        <div className="min-h-screen">
            <Head>
                <title>日记编辑</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>hello world</div>
            <Field
                rows={2}
                autosize
                type="textarea"
            />
        </div>
    )
}

export const getServerSideProps: GetServerSideProps<Props> = async (context) => {
    const config = await getDiaryConfig()

    if (!config) return {
        redirect: { statusCode: 302, destination: '/error/NO_CONFIG' }
    }

    const { writeDiaryButtonColors } = config
    const randIndex = Math.floor(Math.random() * (writeDiaryButtonColors?.length))

    return {
        props: { buttonColor: writeDiaryButtonColors[randIndex] }
    }
}

export default Home