
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/AppConfig'
export type * from './models/Attachment'
export type * from './models/Article'
export type * from './models/Tag'
export type * from './commonInputTypes'