name: release

on:
  push:
    tags:
      - "*"

jobs:
  build-publish-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Get Version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"

      - name: Check docker version
        run: docker -v

      - name: Build the Docker image
        run: docker build -t hopgoldy/cube-diary:${{ env.PACKAGE_VERSION }} .

      - name: Log in to Docker Hub
        run: docker login -u hopgoldy -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Docker image
        run: docker push hopgoldy/cube-diary:${{ env.PACKAGE_VERSION }}
