name: release

on:
  push:
    tags:
      - "*"

jobs:
  build-publish-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: hopgoldy
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: hopgoldy/cube-diary
          tags: |
            type=semver,pattern={{version}}
          flavor: |
            latest=auto

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
